# Generated by Django 5.2.17 on 2026-08-29 17:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('slug', models.SlugField(unique=True)),
                ('sport', models.CharField(choices=[('wingfoil', 'Wingfoil'), ('kitesurf', 'Kitesurf'), ('yoga', 'Yoga'), ('volley', 'Vóley'), ('other', 'Otro')], max_length=20, verbose_name='deporte')),
                ('summary', models.CharField(max_length=220, verbose_name='resumen')),
                ('description', models.TextField(verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio orientativo')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duración en minutos')),
                ('level', models.CharField(default='Todos los niveles', max_length=100, verbose_name='nivel')),
                ('equipment_included', models.BooleanField(default=False, verbose_name='material incluido')),
                ('equipment_details', models.CharField(blank=True, max_length=180, verbose_name='detalle del material')),
                ('location', models.CharField(default='Tarifa', max_length=160, verbose_name='ubicación')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacada')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['sport', 'title'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('city', models.CharField(default='Tarifa', max_length=100, verbose_name='ciudad')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'escuela',
                'verbose_name_plural': 'escuelas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=140, verbose_name='nombre completo')),
                ('contact', models.CharField(max_length=160, verbose_name='email o teléfono')),
                ('preferred_date', models.DateField(verbose_name='fecha preferida')),
                ('participants', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='participantes')),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='nivel')),
                ('notes', models.TextField(blank=True, verbose_name='comentario')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('contacted', 'Contactada'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='new', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='marketplace.activity', verbose_name='actividad')),
            ],
            options={
                'verbose_name': 'solicitud de reserva',
                'verbose_name_plural': 'solicitudes de reserva',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='marketplace.school', verbose_name='escuela'),
        ),
    ]
